# operator

In [7]:
import numpy as np
a = np.array([1,2,3,4])
a + 1 

array([2, 3, 4, 5])

In [3]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [4]:
b = np.ones(4) + 1

In [5]:
# element wise substarction
a - b

array([-1.,  0.,  1.,  2.])

In [6]:
a * b

array([2., 4., 6., 8.])

In [8]:
c= np.diag([1,23,4,5])
print(c*c)
print("**************************")
print(c.dot(c))

[[  1   0   0   0]
 [  0 529   0   0]
 [  0   0  16   0]
 [  0   0   0  25]]
**************************
[[  1   0   0   0]
 [  0 529   0   0]
 [  0   0  16   0]
 [  0   0   0  25]]


In [9]:
 a == b

array([False,  True, False, False])

In [10]:
a > b

array([False, False,  True,  True])

In [11]:
np.array_equal(a,b)

False

In [12]:
np.array_equal(b,c)

False

In [10]:
a = np.array([10,2,3,4,1,7,8,8])
a.argmin()   

4

In [ ]:
a = np.array([])

In [11]:
a.mean()

5.375

In [14]:
a.std()

3.07967124868873