In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

862 µs ± 15.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [2]:
a = np.arange(1000)
%timeit a**2

3.5 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# create numpy array

In [4]:
a = np.array([1,2,3,45,5])
a

array([ 1,  2,  3, 45,  5])

In [5]:
a.ndim

1

In [6]:
a.shape

(5,)

In [7]:
len(a)

5

In [9]:
#2D array
b = np.array([[2,3,4],[5,6,7]])
b

array([[2, 3, 4],
       [5, 6, 7]])

In [10]:
b.ndim

2

In [13]:
b.shape

(2, 3)

In [14]:
len(b)

2

In [16]:
#3D array
c = np.array([[[2,3],[3,5]],[[7,5],[6,2]]])

In [17]:
c.ndim

3

In [18]:
c.shape

(2, 2, 2)

# function for creating array

In [22]:
# arange function
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b = np.arange(0,10,2)
b

array([0, 2, 4, 6, 8])

In [26]:
a = np.linspace(0,1,6)  #start , end ,number of point
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [27]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [32]:
  # diagonal matrix
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [33]:
np.diag(a) # extracting the dIAGNAL element

array([1, 2, 3, 4])

In [35]:
# creating  a array using random

#create an array
a = np.random.rand(4) # uniform distrubuted random number
a

array([0.62286609, 0.94618164, 0.00270975, 0.52897877])

# datatypes

In [36]:
a = np.arange(10)
a.dtype

dtype('int32')

In [39]:
# explicitly specify dta type
a = np.arange(10,dtype='float64')
a
a.dtype

dtype('float64')

In [41]:
a = np.zeros((3,3))
a
a.dtype

dtype('float64')

In [42]:
d = np.array([1+2j, 2+4j])
d

array([1.+2.j, 2.+4.j])

In [43]:
# indexing and slicing
a = np.arange(10)
print(a[5])

5


In [49]:
a = np.diag([1,2,3])
print(a[2,2])


3


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
# slicing

In [53]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [55]:
np.shares_memory(a,b)

False

In [56]:
#random NUMBER 
a = np.random.randint(0,20,15)
a

array([18,  1, 11, 15, 18, 17,  3, 15,  1, 12, 13,  9, 19, 13, 11])

In [57]:
mask = (a%2 == 0)

In [58]:
mask

array([ True, False, False, False,  True, False, False, False, False,
        True, False, False, False, False, False])